steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-f', '.gcp/Dockerfile.cloudrun',
    '-t', 'gcr.io/$PROJECT_ID/puppeteer-glb-renderer:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/puppeteer-glb-renderer:latest',
    '.'
  ]

# Push Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/puppeteer-glb-renderer']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'puppeteer-glb-renderer'
  - '--image'
  - 'gcr.io/$PROJECT_ID/puppeteer-glb-renderer:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--memory'
  - '4Gi'
  - '--cpu'
  - '2'
  - '--timeout'
  - '300s'
  - '--max-instances'
  - '50'
  - '--min-instances'
  - '0'
  - '--concurrency'
  - '10'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'NODE_ENV=production,PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome'

# Optional: Update traffic to new revision
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'services'
  - 'update-traffic'
  - 'puppeteer-glb-renderer'
  - '--to-latest'
  - '--region'
  - 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'